version: "3.9"

services:
  rio_erp_db:
    image: postgres:18
    container_name: rio_erp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4568
      POSTGRES_DB: erp_diplom
    ports:
      - "5434:5432"   # порт для нового Postgres
    volumes:
      - rio_db_data:/var/lib/postgresql   # ✅ правильний mount для Postgres 18+
    networks:
      - rio_erp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d erp_diplom"]
      interval: 10s
      timeout: 5s
      retries: 5

  rio_backend1:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rio_backend1
    restart: always
    depends_on:
      rio_erp_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:4568@rio_erp_db:5432/erp_diplom
    volumes:
      - ./backend:/app/backend
    networks:
      - rio_erp_network

  rio_backend2:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rio_backend2
    restart: always
    depends_on:
      rio_erp_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:4568@rio_erp_db:5432/erp_diplom
    volumes:
      - ./backend:/app/backend
    networks:
      - rio_erp_network

  rio_node:
    image: node:18
    container_name: rio_node
    restart: always
    working_dir: /app
    volumes:
      - ./node:/app
    command: ["node", "server.js"]
    depends_on:
      - rio_backend1
      - rio_backend2
    ports:
      - "8001:8001"   # порт для Node
    networks:
      - rio_erp_network

  rio_frontend:
    build:
      context: ./frontend_rio
    container_name: rio_frontend
    command: python main.py
    volumes:
      - ./frontend_rio:/app
    networks:
      - rio_erp_network
    depends_on:
      - rio_node
    ports:
      - "3001:80"     # порт для фронтенду

  rio_backup:
    image: alpine
    container_name: rio_backup
    restart: always
    volumes:
      - ./backups:/backups
      - ./backup.sh:/backup.sh
    networks:
      - rio_erp_network
    entrypoint: ["/bin/sh", "/backup.sh"]

networks:
  rio_erp_network:
    driver: bridge

volumes:
  rio_db_data:
