"""init schema

Revision ID: 2eb5d365c417
Revises: 588105a9487f
Create Date: 2026-09-04 15:07:24.700822

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb5d365c417'
down_revision = '588105a9487f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
