"""add comment field to journal

Revision ID: 588105a9487f
Revises: 2656132da195
Create Date: 2026-08-27 15:39:29.116073

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588105a9487f'
down_revision = '2656132da195'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', 'comment')
    # ### end Alembic commands ###
