"""опис змін

Revision ID: 83a5efaabfc1
Revises: 2eb5d365c417
Create Date: 2026-09-04 15:11:32.643704

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a5efaabfc1'
down_revision = '2eb5d365c417'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
