"""init schema

Revision ID: fc35bc4a14d0
Revises: 
Create Date: 2026-08-13 16:05:33.221077

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc35bc4a14d0'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_constraint('accounts_code_key', 'accounts', type_='unique')
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.drop_column('accounts', 'code')
    op.alter_column('inventory', 'product',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inventory', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory', 'batch',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_journal_date'), 'journal', ['date'], unique=False)
    op.create_index(op.f('ix_journal_operation'), 'journal', ['operation'], unique=False)
    op.create_index(op.f('ix_journal_status'), 'journal', ['status'], unique=False)
    op.alter_column('legal', 'contract',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('legal', 'partner',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('legal', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('purchases', 'supplier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('purchases', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('purchases', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sales', 'client',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'invoice',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sales', 'invoice',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales', 'client',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('purchases', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('purchases', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('purchases', 'supplier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('legal', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('legal', 'partner',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('legal', 'contract',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_journal_status'), table_name='journal')
    op.drop_index(op.f('ix_journal_operation'), table_name='journal')
    op.drop_index(op.f('ix_journal_date'), table_name='journal')
    op.alter_column('inventory', 'batch',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'product',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('accounts', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.create_unique_constraint('accounts_code_key', 'accounts', ['code'], postgresql_nulls_not_distinct=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
